//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corona_Virus_Disease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int AID { get; set; }
        public string Apic { get; set; }
        public string Aname { get; set; }
        public Nullable<int> Acount { get; set; }
        public string Atype { get; set; }
        public string Warehousing { get; set; }
    }
}
