//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corona_Virus_Disease.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvdDBEntities : DbContext
    {
        public CvdDBEntities()
            : base("name=CvdDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Bmt> Bmt { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Detection> Detection { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Leave> Leave { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Visit> Visit { get; set; }
    }
}
