//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corona_Virus_Disease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detection
    {
        public int DID { get; set; }
        public Nullable<System.DateTime> Dtime { get; set; }
        public string Dresult { get; set; }
        public Nullable<int> StuID { get; set; }
    }
}
