//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corona_Virus_Disease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LID { get; set; }
        public Nullable<int> StuID { get; set; }
        public Nullable<System.DateTime> LstartTime { get; set; }
        public Nullable<System.DateTime> LoverTime { get; set; }
        public string Lreason { get; set; }
        public Nullable<int> Lorschool { get; set; }
        public string Lview { get; set; }
        public Nullable<int> TID { get; set; }
    }
}
